export const SAMPLE_ACTION = 'SAMPLE_ACTION';
export type SAMPLE_ACTION = typeof SAMPLE_ACTION;

export const SAMPLE_ACTION_REQUEST = 'SAMPLE_ACTION_REQUEST';
export type SAMPLE_ACTION_REQUEST = typeof SAMPLE_ACTION_REQUEST;

export const SAMPLE_ACTION_SUCCESS = 'SAMPLE_ACTION_SUCCESS';
export type SAMPLE_ACTION_SUCCESS = typeof SAMPLE_ACTION_SUCCESS;

export const SAMPLE_ACTION_FAILURE = 'SAMPLE_ACTION_FAILURE';
export type SAMPLE_ACTION_FAILURE = typeof SAMPLE_ACTION_FAILURE;

export const CORE_HOST = ''